version: "3.5"

services: 

  mysql:
    image: mysql:5.7
    ports: 
      - "3306:3307"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    command: mysql --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./database/initialize_abiyyu_cakra.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - api-network

  lumen:
    ports:
      - "3030:3030"
    volumes: 
      - .:/var/www/html
      - /var/www/html/vendor
    build: .
    environment:
      # DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
    command: php -S localhost:3030 -t public
    restart: always
    networks:
      - api-network
    depends_on:
      - mysql
  
networks:
  api-network:
    name: api-network