# version: '3.5'

# services: 
#   lumen: 
#     ports:
#       - "3030:8090" 
#     volumes:
#       - .:/var/www/html/
#       - /var/www/html/vendor/
#     build: .
#     command: php -S lumen:8090 -t public 
#     restart: always
#     depends_on:
#       - db
#   db: 
#     image: mysql:5.7
#     container_name: mysql
#     restart: always
#     environment:
#       - MYSQL_USER=${DB_USERNAME}
#       - MYSQL_DATABASE=${DB_DATABASE}
#       - MYSQL_PASSWORD=${DB_PASSWORD}
#       - MYSQL_ROOT_PASSWORD=my_secret_pw
#     command: --default-authentication-plugin=mysql_native_password
#     volumes: 
#       - ./database/mysql-data:/var/lib/mysql:rw
# volumes:
#   mysql-data:

#     # adminer:
#     # image: adminer
#     # restart: always
#     # ports:
#     #   - 8080:8080